name: Run Tests

on :
  push:
    branches:
      - main


jobs:
  run_tests:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: http_database_env
          environment-file: environment.yml
          auto-activate-base: false
      - run: |
          conda info

