name: Run Tests

on :
  push:
    branches:
      - feature/adding_workflows



jobs:
  example-3:
    defaults:
      run:
        shell: bash -el {0} # Set the default shell to bash

  run_tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Miniconda and create environment from environment.yml
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: http_database_env
          auto-activate-base: false

      # Run a command to display Conda information (or any other command)
      - name: Show Conda Info
        run: conda info

      - name: list conda packages
        run: conda env list

      - name: conda init
        run: conda init

      - name: activate conda environment
        run: conda activate http_database_env

        # Run the tests
      - name: Run tests
        run: pytest src/test_server.py



