name: Run Tests

on :
  push:
    branches:
      - feature/adding_workflows



jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      - name: list packages
        run: ls

      # Set up Miniconda and create environment from environment.yml
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: http_database_env
          environment-file: environment.yml
          auto-activate-base: false

      # Run a command to display Conda information (or any other command)
      - name: Show Conda Info
        run: conda info

      - name: List Conda Environments
        run: |
          conda env list
          conda info

      # Ensure the Conda environment is activated
      - name: Ensure Conda Environment
        shell: bash -l {0}
        run: |
          source ~/.bashrc
          conda activate http_database_env
          conda info
          conda env list
          pytest src/test_server.py


